### ISSUE TITLE
Sys Path hard coded - sys.path.append('c:\AngelSmartApi\SmartApi')

### ISSUE THREAD

**Issue by kjoth** [angelbroking-github/smartapi-python#4]
Hi, 

The below path is hardcoded sys.path.append('c:\AngelSmartApi\SmartApi'). Which is not working when trying to import, each system has different path for python packages.

Example: I'm using Mac, where the below path c:\AngelSmartApi\SmartApi' doesnt exists, but it was added to the sys.path also getting the import error

import smartapi.smartConnect

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-a13f9dab5823> in <module>
----> 1 import smartapi.smartConnect

~/opt/anaconda3/lib/python3.6/site-packages/smartapi/smartConnect.py in <module>
      9 import logging
     10 import datetime
---> 11 import smartExceptions
     12 import requests
     13 from requests import get

ModuleNotFoundError: No module named 'smartExceptions'

**Comment by vrushalikapse** [comment]
The hard coded sys path is now removed

**Comment by kjoth** [comment]
Let me try it out and post the update
