### ISSUE TITLE
SmartWebSocket connect is taking years to connect

### ISSUE THREAD

**Issue by VineetKillerX** [angelbroking-github/smartapi-python#43]
I tried using WebSocket Connect method to get live feeds in the market but I am unable to do so.

Sample Code:

from smartapi import SmartWebSocket

FEED_TOKEN="xxxxx"
CLIENT_CODE="xxxx"
token="nse_cm|2885&nse_cm|1594&nse_cm|11536&nse_cm|3045" #"nse_cm|2885&nse_cm|1594&nse_cm|11536"
task="mw" #"mw"|"sfi"|"dp"
ss = SmartWebSocket(FEED_TOKEN, CLIENT_CODE)

def on_tick(ws, tick):
    print("Ticks: {}".format(tick))

def on_connect(ws, response):
    ws.websocket_connection() # Websocket connection  
    ws.send_request(token,task) 
    
def on_close(ws, code, reason):
    ws.stop()

# Assign the callbacks.
ss.on_ticks = on_tick
ss.on_connect = on_connect
ss.on_close = on_close

ss.connect()

**Comment by ankursingh081** [comment]
update smartapi-python to 1.2.7 fixed the issue for me

**Comment by VineetKillerX** [comment]
Thanks it solved for me, Marking this issue as closed.
