### ISSUE TITLE
Websocket Order Status not working

### ISSUE THREAD

**Issue by ramkolam** [angelbroking-github/smartapi-python#50]
not receiving any updates on subscribing to order_feed

**Comment by VineetKillerX** [comment]
Can you share a sample code for that? I cant see what task should I use to subscribe to order feeds, Supported tasks are mq, dp, sfi.

**Comment by techs07** [comment]
any update ?

**Comment by aakash2610** [comment]
Hey @ramkolam,

Is this working now? If yes, can you please share a snippet of how to do so?

Thanks,

**Comment by virajkadam** [comment]
@ramkolam kindly provide result, explanation to problem or solution to it before closing.
