### ISSUE TITLE
AMX Error on login request

### ISSUE THREAD

**Issue by arun-vunet** [angelbroking-github/smartapi-python#6]
Hi, 
   I am getting the following error when I try to login using my valid Angel credentials. 

{'status': False, 'message': 'YOUR USER ID OR PASSWORD IS INVALID', 'errorcode': 'AB1007', 'data': None}

According to the Smart API documentation, 
AB1007 -> AMX Error 

What does this mean?

**Comment by rjbanna** [comment]
@arun-vunet @vrushalikapse @angelbroking-github I'm also getting the same issue. I also tried the given python code but it is returning the webpage not the JSON, stating that I need to enable javascript and I have enabled the javascript in my browser. It's little confusing.

**Comment by arun-vunet** [comment]
Not see the issue now

**Comment by rajanprabu** [comment]
I still have the same error. 

/rest/auth/angelbroking/user/v1/loginByPassword
https://apiconnect.angelbroking.com/rest/auth/angelbroking/user/v1/loginByPassword
The Response Content b'{"status":false,"message":"YOUR USER ID OR PASSWORD IS INVALID","errorcode":"AB1007","data":null}'
