### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by K-Poonam** [angelbroking-github/smartapi-python#61]
getting error in below line though i am giving correct username ,password and api key but 
feed_token = None
token_map = None. can anyone help plz

----> 8 refreshToken= data['data']['refreshToken']
      9 
     10 #fetch the feedtoken

TypeError: 'NoneType' object is not subscriptable

**Comment by back-2-hack** [comment]
I am getting same error and can tell me to how do I get client ID in detail...
Don't just tell me to see the login ID because I logged in with my e-mail ID and not with any kind of login ID ...
