### ISSUE TITLE
You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by builder35abhishek** [angelbroking-github/smartapi-python#7]
Hi Team,

I followed steps provided in document but getting strange error,
I am digging out at my end as well.
Can you check from your end as well?

/rest/auth/angelbroking/user/v1/loginByPassword
https://smartapi.angelbroking.com/rest/auth/angelbroking/user/v1/loginByPassword
The Response Content b'<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="SmartAPI Developer Portal"/><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="https://code.jquery.com/jquery-3.5.1.min.js"></script><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet"><link href="css/style.css" rel="stylesheet" media="all"><script src="/rainbow/rainbow.min.js"></script><script>Rainbow.extend("json",[{matches:{1:"key",2:"colon",3:"value"},pattern:/(.*?)(:)\\s+?(.*?),?$/gm}],!0),Rainbow.color()</script><script src="https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver"></script><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>SmartAPI</title><link href="/static/css/main.8a275228.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script async src="https://www.googletagmanager.com/gtag/js?id=G-DZM6GZD54M"></script><script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-DZM6GZD54M")</script><script>!function(e){function r(r){for(var n,a,c=r[0],p=r[1],l=r[2],i=0,s=[];i<c.length;i++)a=c[i],Object.prototype.hasOwnProperty.call(o,a)&&o[a]&&s.push(o[a][0]),o[a]=0;for(n in p)Object.prototype.hasOwnProperty.call(p,n)&&(e[n]=p[n]);for(f&&f(r);s.length;)s.shift()();return u.push.apply(u,l||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,c=1;c<t.length;c++){var p=t[c];0!==o[p]&&(n=!1)}n&&(u.splice(r--,1),e=a(a.s=t[0]))}return e}var n={},o={1:0},u=[];function a(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,a),t.l=!0,t.exports}a.m=e,a.c=n,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(e,r){if(1&r&&(e=a(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)a.d(t,n,function(r){return e[r]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/";var c=this["webpackJsonpacc-react-app"]=this["webpackJsonpacc-react-app"]||[],p=c.push.bind(c);c.push=r,c=c.slice();for(var l=0;l<c.length;l++)r(c[l]);var f=p;t()}([])</script><script src="/static/js/2.535b646b.chunk.js"></script><script src="/static/js/main.f8b1983c.chunk.js"></script></body></html>'
Traceback (most recent call last):
  File "/home/abhishek/fyers/app/lib/python3.8/site-packages/smartapi/smartConnect.py", line 195, in _request
    data = json.loads(r.content.decode("utf8"))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 10, in <module>
    data = obj.generateSession("A33543","A57hjfgilder00")
  File "/home/abhishek/fyers/app/lib/python3.8/site-packages/smartapi/smartConnect.py", line 235, in generateSession
    loginResultObject=self._postRequest("api.login",params)
  File "/home/abhishek/fyers/app/lib/python3.8/site-packages/smartapi/smartConnect.py", line 227, in _postRequest
    return self._request(route, "POST", params)
  File "/home/abhishek/fyers/app/lib/python3.8/site-packages/smartapi/smartConnect.py", line 198, in _request
    raise ex.DataException("Couldn't parse the JSON response received from the server: {content}".format(
smartapi.smartExceptions.DataException: Couldn't parse the JSON response received from the server: b'<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="SmartAPI Developer Portal"/><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="https://code.jquery.com/jquery-3.5.1.min.js"></script><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet"><link href="css/style.css" rel="stylesheet" media="all"><script src="/rainbow/rainbow.min.js"></script><script>Rainbow.extend("json",[{matches:{1:"key",2:"colon",3:"value"},pattern:/(.*?)(:)\\s+?(.*?),?$/gm}],!0),Rainbow.color()</script><script src="https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver"></script><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>SmartAPI</title><link href="/static/css/main.8a275228.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script async src="https://www.googletagmanager.com/gtag/js?id=G-DZM6GZD54M"></script><script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-DZM6GZD54M")</script><script>!function(e){function r(r){for(var n,a,c=r[0],p=r[1],l=r[2],i=0,s=[];i<c.length;i++)a=c[i],Object.prototype.hasOwnProperty.call(o,a)&&o[a]&&s.push(o[a][0]),o[a]=0;for(n in p)Object.prototype.hasOwnProperty.call(p,n)&&(e[n]=p[n]);for(f&&f(r);s.length;)s.shift()();return u.push.apply(u,l||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,c=1;c<t.length;c++){var p=t[c];0!==o[p]&&(n=!1)}n&&(u.splice(r--,1),e=a(a.s=t[0]))}return e}var n={},o={1:0},u=[];function a(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,a),t.l=!0,t.exports}a.m=e,a.c=n,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(e,r){if(1&r&&(e=a(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)a.d(t,n,function(r){return e[r]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/";var c=this["webpackJsonpacc-react-app"]=this["webpackJsonpacc-react-app"]||[],p=c.push.bind(c);c.push=r,c=c.slice();for(var l=0;l<c.length;l++)r(c[l]);var f=p;t()}([])</script><script src="/static/js/2.535b646b.chunk.js"></script><script src="/static/js/main.f8b1983c.chunk.js"></script></body></html>'

**Comment by arun-vunet** [comment]
@vrushalikapse This is a blocker which is preventing user from getting the full use of the SmartAPIs. Would be great if this can be addressed ASAP

**Comment by builder35abhishek** [comment]
Able to login after updating to version smartapi-python 1.0.6
